### ISSUE TITLE
File download support if possible

### ISSUE THREAD

**Issue by zweicoder** [jiahaog/Revenant#5]
Unfortunately just using `openPage` doesn't allow `Revenant` to download files, the URL simply does not change and `onResourceReceived` fails to get anything in my case. This could be resolved (I have not tested it) by the answers [here](http://stackoverflow.com/questions/31564215/how-to-download-a-csv-file-using-phantomjs)

**Comment by jiahaog** [comment]
Feature added in #8 and #9, thanks!
